// -----------------------------------------------------------------------------
// file: sys/kernel.js
// -----------------------------------------------------------------------------
// The main libraries are now loaded globally from index.html.
import http from 'https://unpkg.com/isomorphic-git/http/web/index.js';
// The new AST parser, which uses nearley.js
import parse from './parser.js';

/**
 * Kernel is the main class for the web terminal.
 * It now functions as an interpreter for the Abstract Syntax Tree (AST)
 * generated by the parser.
 */
export default class Kernel {
    constructor(options = {}) {
        // --- Default Configuration ---
        const defaults = {
            container: document.getElementById('terminal'),
            welcomeMessage: 'Welcome to the QRx Kernel.\r\n',
            repo: {
                commands: '../sys/cmd/index.js',
                inputHandler: '../sys/handlers/input.js',
                keyHandlers: '../sys/handlers/keys/index.js'
            },
            gitConfig: { dir: '/', corsProxy: 'https://cors.isomorphic-git.org' }
        };
        // Deep merge of defaults and options
        this.config = { 
            ...defaults, 
            ...options, 
            repo: { ...defaults.repo, ...(options.repo || {}) },
            gitConfig: { ...defaults.gitConfig, ...(options.gitConfig || {}) },
        };

        // --- Core Components & State ---
        this.fs = new window.LightningFS('main_qrxworld_qrx'); // Namespaced filesystem
        this.pfs = this.fs.promises;
        this.git = window.isomorphicGit; 
        this.http = http;
        this.term = new window.Terminal({
            cursorBlink: true, fontSize: 14, fontFamily: 'monospace',
            theme: { background: '#1e1e1e', foreground: '#d4d4d4', cursor: '#d4d4d4' },
            allowTransparency: true,
        });

        // Bind core I/O methods to ensure 'this' is always correct.
        this.write = this.write.bind(this);
        this.writeln = this.writeln.bind(this);
        
        this.term.open(this.config.container);
        this.term.focus();

        this.cwd = '/'; this.env = {};
        this.history = []; this.historyIndex = -1;
        this.commandBuffer = ''; this.commandInProgress = false;
        
        this.lastExitStatus = 0;
        
        this.commands = {}; this.inputHandler = null;
        this.currentProcess = null;

        // --- Initialization ---
        this.init().catch(err => {
            console.error("Initialization failed:", err);
            this.writeln(`\x1B[1;31mFATAL: Initialization failed. Check console for details.\x1B[0m`);
            this.commandInProgress = true;
        });
    }

    async init() {
        await this.pfs.mkdir('/sys/cmd').catch(e => {});
        await this.loadModules();
        this.term.onKey((keyEvent) => {
            if (this.inputHandler) {
                this.inputHandler.handle(this, keyEvent);
            }
        });
        this.term.write(this.config.welcomeMessage);
        this.prompt();
    }

    async loadModules() {
        this.writeln('Loading modules...');
        await this.loadInputHandler(this.config.repo.inputHandler);
        await this.loadKeyHandlers(this.config.repo.keyHandlers);
        await this.loadCommandManifest(this.config.repo.commands);
        this.writeln('All modules loaded.');
    }
    
    async loadInputHandler(url) {
        try {
            const { default: InputHandler } = await import(url);
            this.inputHandler = new InputHandler();
        } catch (error) { this.writeln(`\x1B[1;31mFATAL: Could not load Input Handler from ${url}\x1B[0m`); console.error(error); }
    }
    
    async loadKeyHandlers(url) {
        if (!this.inputHandler) return;
        try {
            const { default: keyManifest } = await import(url);
            for (const keyName in keyManifest) {
                const path = keyManifest[keyName];
                const handlerModule = await import(path);
                this.inputHandler.register(keyName, handlerModule.default);
            }
        } catch (error) { this.writeln(`\x1B[1;31mFATAL: Could not load Key Handlers from ${url}\x1B[0m`); console.error(error); }
    }

    async loadCommandManifest(url) {
        try {
            const { default: commandRegistry } = await import(url);
            this.commands = commandRegistry;
        } catch (error) { this.writeln(`\x1B[1;31mFATAL: Could not load Command Manifest from ${url}\x1B[0m`); console.error(error); }
    }

    prompt() {
        this.commandBuffer = '';
        this.commandInProgress = false;
        this.term.focus();
        this.term.write(`\r\n\x1B[1;32muser@host\x1B[0m:\x1B[1;34m${this.cwd}\x1B[0m$ `);
    }

    write(data) { this.term.write(String(data).replace(/\n/g, '\r\n')); }
    writeln(data) { this.write(data + '\r\n'); }
    
    cancelCurrentProcess() {
        if (this.currentProcess?.cancel) {
            this.currentProcess.cancel();
        } else {
            this.writeln('^C');
            this.prompt();
        }
    }

    async runCommand(line) {
        this.commandInProgress = true;
        const ast = parse(line);

        try {
            for (const node of ast) {
                const { stdout, status } = await this.executeNode(node);
                if (stdout && !node.redirection) {
                    this.write(stdout);
                }
            }
        } catch (error) {
            this.writeln(`\x1B[1;31mError: ${error.message}\x1B[0m`);
            console.error(error);
        } finally {
            this.commandInProgress = false;
            this.prompt();
        }
    }

    async executeNode(node, stdin = null) {
        if (!node) return { stdout: '', status: 0 };
        
        let result = { stdout: '', status: 0 };

        switch (node.type) {
            case 'error':
                result = { stdout: `-qrx: parse error: ${node.message}\n`, status: 2 };
                break;
            case 'pipeline':
                const leftResult = await this.executeNode(node.from, stdin);
                result = await this.executeNode(node.to, leftResult.stdout);
                break;
            case 'group':
                const groupOutputBuffer = [];
                let groupStatus = 0;
                for (const cmdNode of node.commands) {
                    const subResult = await this.executeNode(cmdNode, stdin);
                    groupOutputBuffer.push(subResult.stdout);
                    groupStatus = subResult.status;
                }
                result = { stdout: groupOutputBuffer.join(''), status: groupStatus };
                break;
            case 'command':
                const buffer = [];
                const originalWrite = this.write;
                const originalWriteln = this.writeln;
                this.write = (data) => buffer.push(data);
                this.writeln = (data) => buffer.push(data + '\n');
                
                let commandStatus = 0;
                try {
                    commandStatus = await this.executeSingleCommand(node, stdin);
                } finally {
                    this.write = originalWrite;
                    this.writeln = originalWriteln;
                }
                result = { stdout: buffer.join(''), status: commandStatus };
                break;
        }

        if (node.redirection) {
            const { mode, file } = node.redirection;
            const path = this.resolvePath(file);
            try {
                if (mode === 'append') {
                    const existing = await this.pfs.readFile(path, 'utf8').catch(() => '');
                    await this.pfs.writeFile(path, existing + result.stdout);
                } else {
                    await this.pfs.writeFile(path, result.stdout);
                }
                result.stdout = '';
            } catch (e) {
                this.writeln(`-qrx: ${file}: ${e.message}`);
                result.status = 1;
            }
        }

        this.lastExitStatus = result.status;
        return result;
    }

    /**
     * The lowest-level execution function for a single command.
     * MODIFIED to perform variable expansion for $?.
     * @param {object} commandObject - A command node from the AST.
     * @param {string|null} stdin - Piped input.
     * @returns {Promise<number>} A promise that resolves to the command's exit status.
     */
    async executeSingleCommand({ name, args }, stdin = null) {
        // --- NEW: Variable Expansion Step ---
        // Before executing, we expand any special variables in the arguments.
        const expandedArgs = args.map(arg => {
            if (arg === '$?') {
                return String(this.lastExitStatus);
            }
            // Future variables like $HOME could be added here.
            return arg;
        });
        // --- END of new block ---

        if (!name) {
            if (stdin !== null) this.write(stdin);
            return 0;
        }
        
        const assignMatch = name.match(/^([a-zA-Z_][a-zA-Z0-9_]*)=(.+)/s);
        if (assignMatch && expandedArgs.length === 0) {
            this.env[assignMatch[1]] = assignMatch[2].replace(/^['"]|['"]$/g, '');
            return 0;
        }

        const builtin = this.commands[name];
        if (builtin?.run) {
            let status = 0;
            try {
                // We pass the *expanded* arguments to the command
                const commandPromise = builtin.run(this, expandedArgs, stdin);
                this.currentProcess = commandPromise;
                const commandResult = await commandPromise;
                
                if (typeof commandResult === 'number') {
                    status = commandResult;
                }
            } catch (err) {
                this.writeln(`-qrx: ${name}: ${err.message}`);
                status = 1;
            } finally {
                this.currentProcess = null;
            }
            return status;
        }
        
        return this.handleBuiltins(name, expandedArgs);
    }
    
    handleBuiltins(name, args) {
        switch (name) {
            case 'help':
                const cmds = Object.keys(this.commands).sort().join(', ');
                this.writeln(`Builtins: help, clear. Commands: ${cmds}`);
                return 0;
            case 'clear':
                this.term.clear();
                return 0;
            case '':
                return 0;
            default:
                this.writeln(`command not found: ${name}`);
                return 127;
        }
    }

    resolvePath(path) {
        if (!path || path === '.') return this.cwd;
        if (path.startsWith('/')) return path.replace(/\/+/g, '/');
        const separator = this.cwd === '/' ? '' : '/';
        return `${this.cwd}${separator}${path}`;
    }
}
